pdflatex ReviewPresentation
bibtex ReviewPresentation
pdflatex ReviewPresentation
pdflatex ReviewPresentation

makeindex ReviewPresentation.nlo -s nomencl.ist -o ReviewPresentation.nls

pdflatex ReviewPresentation
pdflatex ReviewPresentation